//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Region {
    
    private string nameField;
    
    private string mutedField;
    
    private string opaqueField;
    
    private string lockedField;
    
    private string videolockedField;
    
    private string automaticField;
    
    private string wholefileField;
    
    private string importField;
    
    private string externalField;
    
    private string syncmarkedField;
    
    private string leftofsplitField;
    
    private string rightofsplitField;
    
    private string hiddenField;
    
    private string positionlockedField;
    
    private string validtransientsField;
    
    private string startField;
    
    private string lengthField;
    
    private string positionField;
    
    private string beatField;
    
    private string syncpositionField;
    
    private string ancestralstartField;
    
    private string ancestrallengthField;
    
    private string stretchField;
    
    private string shiftField;
    
    private string positionallockstyleField;
    
    private string layeringindexField;
    
    private string tagsField;
    
    private string contentsField;
    
    private string startbeatsField;
    
    private string lengthbeatsField;
    
    private string idField;
    
    private string typeField;
    
    private string firsteditField;
    
    private string source0Field;
    
    private string mastersource0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string muted {
        get {
            return this.mutedField;
        }
        set {
            this.mutedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opaque {
        get {
            return this.opaqueField;
        }
        set {
            this.opaqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locked {
        get {
            return this.lockedField;
        }
        set {
            this.lockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("video-locked")]
    public string videolocked {
        get {
            return this.videolockedField;
        }
        set {
            this.videolockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string automatic {
        get {
            return this.automaticField;
        }
        set {
            this.automaticField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("whole-file")]
    public string wholefile {
        get {
            return this.wholefileField;
        }
        set {
            this.wholefileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string import {
        get {
            return this.importField;
        }
        set {
            this.importField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string external {
        get {
            return this.externalField;
        }
        set {
            this.externalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sync-marked")]
    public string syncmarked {
        get {
            return this.syncmarkedField;
        }
        set {
            this.syncmarkedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("left-of-split")]
    public string leftofsplit {
        get {
            return this.leftofsplitField;
        }
        set {
            this.leftofsplitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("right-of-split")]
    public string rightofsplit {
        get {
            return this.rightofsplitField;
        }
        set {
            this.rightofsplitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hidden {
        get {
            return this.hiddenField;
        }
        set {
            this.hiddenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("position-locked")]
    public string positionlocked {
        get {
            return this.positionlockedField;
        }
        set {
            this.positionlockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("valid-transients")]
    public string validtransients {
        get {
            return this.validtransientsField;
        }
        set {
            this.validtransientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string beat {
        get {
            return this.beatField;
        }
        set {
            this.beatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sync-position")]
    public string syncposition {
        get {
            return this.syncpositionField;
        }
        set {
            this.syncpositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("ancestral-start")]
    public string ancestralstart {
        get {
            return this.ancestralstartField;
        }
        set {
            this.ancestralstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("ancestral-length")]
    public string ancestrallength {
        get {
            return this.ancestrallengthField;
        }
        set {
            this.ancestrallengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stretch {
        get {
            return this.stretchField;
        }
        set {
            this.stretchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shift {
        get {
            return this.shiftField;
        }
        set {
            this.shiftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("positional-lock-style")]
    public string positionallockstyle {
        get {
            return this.positionallockstyleField;
        }
        set {
            this.positionallockstyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("layering-index")]
    public string layeringindex {
        get {
            return this.layeringindexField;
        }
        set {
            this.layeringindexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contents {
        get {
            return this.contentsField;
        }
        set {
            this.contentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("start-beats")]
    public string startbeats {
        get {
            return this.startbeatsField;
        }
        set {
            this.startbeatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("length-beats")]
    public string lengthbeats {
        get {
            return this.lengthbeatsField;
        }
        set {
            this.lengthbeatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("first-edit")]
    public string firstedit {
        get {
            return this.firsteditField;
        }
        set {
            this.firsteditField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("source-0")]
    public string source0 {
        get {
            return this.source0Field;
        }
        set {
            this.source0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("master-source-0")]
    public string mastersource0 {
        get {
            return this.mastersource0Field;
        }
        set {
            this.mastersource0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class midiman {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Playlists", typeof(midimanPlaylists), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("Region", typeof(Region))]
    [System.Xml.Serialization.XmlElementAttribute("Regions", typeof(midimanRegions), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("Sources", typeof(midimanSources), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class midimanPlaylists {
    
    private midimanPlaylistsPlaylist[] playlistField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Playlist", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public midimanPlaylistsPlaylist[] Playlist {
        get {
            return this.playlistField;
        }
        set {
            this.playlistField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class midimanPlaylistsPlaylist {
    
    private Region[] regionField;
    
    private string idField;
    
    private string nameField;
    
    private string typeField;
    
    private string origtrackidField;
    
    private string sharedwithidsField;
    
    private string frozenField;
    
    private string combineopsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Region")]
    public Region[] Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("orig-track-id")]
    public string origtrackid {
        get {
            return this.origtrackidField;
        }
        set {
            this.origtrackidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("shared-with-ids")]
    public string sharedwithids {
        get {
            return this.sharedwithidsField;
        }
        set {
            this.sharedwithidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string frozen {
        get {
            return this.frozenField;
        }
        set {
            this.frozenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("combine-ops")]
    public string combineops {
        get {
            return this.combineopsField;
        }
        set {
            this.combineopsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class midimanRegions {
    
    private Region[] regionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Region")]
    public Region[] Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class midimanSources {
    
    private midimanSourcesSource[] sourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Source", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public midimanSourcesSource[] Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class midimanSourcesSource {
    
    private string nameField;
    
    private string takeidField;
    
    private string typeField;
    
    private string flagsField;
    
    private string idField;
    
    private string originField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("take-id")]
    public string takeid {
        get {
            return this.takeidField;
        }
        set {
            this.takeidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string origin {
        get {
            return this.originField;
        }
        set {
            this.originField = value;
        }
    }
}
